### ISSUE TITLE
Crash when reading wav file

### ISSUE THREAD

**Issue by bornej** [savonet/ocaml-mm#10]
Hi, I can't correctly play wav files in (mm 0.6.0)
- Description of the problem:

     The wav player example provided with the mm library crashes with:
     `Fatal error: exception Invalid_argument("convert_native: output buffer too small")`
     when reaching the end of the wav files I try to read.

- Program to reproduce:
I modified the example to use pulseaudio... But it doesn't matter here...
```
       let () =
         let fname = Sys.argv.(1) in
         let f = new Audio.IO.Reader.of_wav_file fname in
         let pulse = new MMPulseaudio.writer "test" "jack_out" f#channels f#sample_rate in
         let blen = 1024 in
         let buf = Audio.create f#channels blen in
         Printf.printf "Opened WAV file with %d channels at %dHz.\n%!" f#channels f#sample_rate;
         let loop = ref true in
         while !loop do
           let r = f#read buf in
           loop := r <> 0;
           (*pulse#write (Audio.to_array buf) 0 blen*)
         done;
         pulse#close;
         f#close
```
- What I tried:
I tested with different files with different formats (16 bit, 24, 32, mono, stereo), and got the same problem.
I tried changing the buffer size to different values (16, 32, 64, ...., 3495).
I read the source for every function involved in this program to see if I could spot something.

I traced back the error to a call to `caml_float_pcm_convert_s16` in `audio_c.c` initiated by `f#read`.

It seems that the test triggering the error have been changed in commit 67675e34adc02914bc3dd34b49041aeb966a68be
from 
`if (dst_off + len > dst_len)`
 to
`if (len + offset > caml_string_length(_src))`

In the new version `dst_len` has been replaced by `lenght(_src)`
I though this test was here to check if the destination buffer was large enough to receive the result of the conversion.
It felt like having a '<' replaced by '>' was a possible typo...
But I might be wrong.

Changing the test seems to "solve" the issue but I don't understand every detail of the functions involved in this (yet)...
For example there is the `*2` factor that I couldn't really explain in `(offset + len)*nc*2`.

Edit: The error isn't raised anymore but the playback stop before the end of
the file. 

Edit 2: In mm.0.5.0 no error is raised but the playback also stops before the end
of the file...

If someone has an idea, or has the same issue...

Best regards.

**Comment by smimram** [comment]
Sorry, I haven't had time to properly review your bug report yet. Why did you close it? Did you find some other way to solve it?

**Comment by bornej** [comment]
Hi, thanks for your answer.
Unfortunately I didn't solve it yet...
I just realized that: 
- when I build a native executable using the makefile you provided with the example I don't have the issue..
- when I build the same executable using dune I get the crash...

As for closing the subject.
I thought It was maybe premature to declare this an issue. I didn't want to bother you with that if problem was on my side...

I will try to investigate why my dune builds don't work and you build works...

**Comment by smimram** [comment]
Thanks, keep us posted!
